---
- name: Prepare VPS for FiveM
  hosts: all_servers
  vars_files:
    - vars/main.yml
  vars:
    - fx_service_name: "fxserver-{{ environment_name }}"
    - mariadb_service_name: "fivem-db-{{ environment_name }}"
    - service_dir_fxserver: "{{ fivem_user_dir }}/{{ environment_name }}"
    - service_dir_mariadb: "/var/fivem/{{ environment_name }}"

  pre_tasks:
    - name: Update apt package index
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install essential packages
      become: true
      ansible.builtin.apt:
        name:
          - git
          - curl
          - iptables
          - iptables-persistent
          - wget
          - screen
          - xz-utils
          - libatomic1
          - libc++-dev
          - libssl-dev
          - zlib1g
          - build-essential
          - docker-compose
          - neovim
        state: present
        update_cache: true
      when: inventory_hostname == 'prod_host'

    - name: Install Docker.io
      become: true
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: inventory_hostname == 'prod_host'

    - name: Enable Docker service
      become: true
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
      when: inventory_hostname == 'prod_host'

    - name: Create fivem group
      become: true
      ansible.builtin.group:
        name: fivem
        state: present
      when: inventory_hostname == 'prod_host'

    - name: Create fivem user
      become: true
      ansible.builtin.user:
        name: fivem
        groups:
          - fivem
          - docker
        home: /home/fivem
        shell: /bin/bash
        password: "{{ fivem_user_password }}"
        # system: true
        create_home: true
      when: inventory_hostname == 'prod_host'

    - name: Add the current user to the Docker and FiveM Admins groups
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker, fivem
        append: true
      when: inventory_hostname == 'prod_host'

    - name: Create the fivem backups directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/fivem_backups"
        state: directory
        mode: "0775"
        owner: "{{ ansible_user_id }}"

    - name: Download server binaries
      become: true
      ansible.builtin.get_url:
        url: "{{ fx_source_download_url }}"
        dest: /home/debian/fx.tar.xz
        mode: "0777"
      retries: 3
      delay: 5
      when: inventory_hostname == 'prod_host'

  tasks:
    - name: Ensure required directories are present
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0775'
        group: fivem
        owner: fivem
      loop:
        - "{{ service_dir_fxserver }}"
        - "{{ service_dir_fxserver }}/server-data"
        - "{{ service_dir_fxserver }}/server"
        - "{{ service_dir_mariadb }}"
        - "{{ service_dir_mariadb }}/mariadb_data"

    - name: Create backup scripts
      become: true
      ansible.builtin.template:
        src: templates/fivem_backup.sh.j2
        dest: "{{ backups_dir }}/fivem_backup_{{ environment_name }}.sh"
        mode: "0755"
        owner: debian
        group: fivem

    - name: Create restore scripts
      become: true
      ansible.builtin.template:
        src: templates/fivem_restore.sh.j2
        dest: "{{ backups_dir }}/fivem_restore_{{ environment_name }}.sh"
        mode: "0755"
        owner: debian
        group: fivem

    - name: Setup systemd service for fxserver
      become: true
      ansible.builtin.template:
        src: templates/service-fxserver.service.j2
        dest: "/etc/systemd/system/fxserver-{{ environment_name }}.service"
        mode: "0600"
        group: fivem
        owner: fivem
      notify:
        - Reload systemd
        - Enable fxserver service

    - name: Setup docker-compose file for txAdmin database
      become: true
      ansible.builtin.template:
        src: templates/docker-compose-mariadb.yml.j2
        dest: "{{ service_dir_mariadb }}/docker-compose.yml"
        mode: "0600"
        group: fivem
        owner: fivem

    - name: Setup systemd service for docker-compose database
      become: true
      ansible.builtin.template:
        src: templates/service-mariadb.service.j2
        dest: "/etc/systemd/system/fivem-db-{{ environment_name }}.service"
        mode: "0600"
        group: fivem
        owner: fivem
      notify:
        - Reload systemd
        - Enable docker-compose-db service

    - name: Ensure iptables rules are applied
      become: true
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item.protocol }}"
        destination_port: "{{ item.port }}"
        jump: ACCEPT
      loop:
        - { protocol: tcp, port: "{{ fivem_port }}" }
        - { protocol: udp, port: "{{ fivem_port }}" }
        - { protocol: tcp, port: "{{ txadmin_port }}" }
        - { protocol: tcp, port: "{{ rcon_port }}" }
        - { protocol: tcp, port: "{{ mariadb_port }}" }
      notify:
        - Save iptables rules

    - name: Enable IP forwarding and NAT rules (required for public availability)
      become: true
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        sysctl_set: true

    # TODO: Get these working
    - name: Allow txAdmin and RCON access for admin group
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        state: present
        regexp: "^%fivem"
        line: "%fivem ALL=(ALL) NOPASSWD: /usr/bin/mysql, /usr/bin/curl, /usr/local/bin/fxadmin-cli"


    - name: Extract FXServer tar file
      become: true
      ansible.builtin.unarchive:
        src: /home/debian/fx.tar.xz
        dest: "{{ service_dir_fxserver }}/server"
        remote_src: true
        group: fivem
        owner: fivem

    - name: Add GitHub to known_hosts
      ansible.builtin.known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        path: /etc/ssh/ssh_known_hosts

# TODO: See if this can be refactored
    - name: Configure Git to treat the directory as safe
      become: true
      ansible.builtin.command:
        cmd: "git config --global --add safe.directory {{ service_dir_fxserver }}/server-data"
      register: github_safe_dir
      changed_when: false

    - name: Clone the server-data
      ansible.builtin.git:
        repo: https://github.com/citizenfx/cfx-server-data.git
        # version: 8-digit hash
        dest: "{{ service_dir_fxserver }}/server-data"
      retries: 3
      delay: 5

    - name: Generate server.cfg template file
      become: true
      ansible.builtin.template:
        src: server.cfg.j2
        dest: "{{ service_dir_fxserver }}/server-data/server.cfg"
        # owner: "{{ fx_service_name }}"
        owner: fivem
        group: fivem
        mode: "0775"

    - name: Generate docker-compose for MariaDB service
      become: true
      ansible.builtin.template:
        src: docker-compose-mariadb.yml.j2
        dest: "{{ service_dir_mariadb }}/docker-compose.yml"
        owner: fivem
        group: fivem
        mode: "0775"

    - name: Generate systemd for databases
      become: true
      ansible.builtin.template:
        src: service-mariadb.service.j2
        dest: /etc/systemd/system/fivem-db-{{ environment_name }}.service
        owner: fivem
        group: fivem
        mode: "0775"

  handlers:

    - name: Save iptables rules
      become: true
      ansible.builtin.command: sudo netfilter-persistent save
      register: iptables_saved
      changed_when: false

    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable fxserver service
      become: true
      ansible.builtin.systemd:
        name: "fxserver-{{ environment_name }}.service"
        enabled: true
        state: started

    - name: Enable docker-compose-db service
      become: true
      ansible.builtin.systemd:
        name: "fivem-db-{{ environment_name }}.service"
        enabled: true
        state: started

    # - name: Save iptables rules
    #   become: true
    #   ansible.builtin.command: iptables-save > /etc/iptables/rules.v4
    #   register: iptables_saved
    #   changed_when: false