---
- name: Prepare GitHubActions after FiveM inital txAdmin setup
  hosts: all_servers
  vars_files:
    - vars/main.yml
  tasks:
    - name: Apply ACLs for `ghactions` on resources directories
      become: true
      ansible.posix.acl:
        path: "/home/fivem/{{ environment_name }}/server/txData/{{ qb_framework_dir }}/resources"
        entity: "{{ gh_actions_username }}"
        etype: user
        permissions: rwx
        state: present
        recursive: true

    - name: Apply ACLs for `ghactions` on server.cfg files
      become: true
      ansible.posix.acl:
        path: "/home/fivem/{{ environment_name }}/server/txData/{{ qb_framework_dir }}/server.cfg"
        entity: "{{ gh_actions_username }}"
        etype: user
        permissions: rwx
        state: present
        recurse: true

    - name: Apply default ACLs for `ghactions` on resources directories
      become: true
      ansible.posix.acl:
        path: "/home/fivem/{{ environment_name }}/server/txData/{{ qb_framework_dir }}/resources/[qb]"
        entity: "{{ gh_actions_username }}"
        etype: user
        permissions: rwx
        state: present
        default: true
