---
- name: Prepare GitHubActions after FiveM inital txAdmin setup
  hosts: production
  vars_files:
    - vars/main.yml
    - name: Apply ACLs for `ghactions` on resources directories
      become: true
      ansible.posix.acl:
        path: "/home/fivem/{{ environment_name }}/server/txData/{{ qb_framework_dir }}/resources"
        entity: "{{ gh_actions_username }}"
        etype: user
        permissions: rwX
        state: present

    - name: Apply ACLs for `ghactions` on server.cfg files
      become: true
      ansible.posix.acl:
        path: "/home/fivem/{{ environment_name }}/server/txData/{{ qb_framework_dir }}/server.cfg"
        entity: "{{ gh_actions_username }}"
        etype: user
        permissions: rwX
        state: present

    - name: Apply default ACLs for `ghactions` on resources directories
      become: true
      ansible.posix.acl:
        path: "/home/fivem/{{ environment_name }}/server/txData/{{ qb_framework_dir }}/resources"
        entity: "{{ gh_actions_username }}"
        etype: user
        permissions: rwX
        state: present
        default: true