environment_name: staging
fivem_server_name: sbstg
fivem_port: 30130
txadmin_port: 40130
rcon_port: 30131
fivem_max_clients: 4
fivem_server_tags: default, deployer, qbcore, qb-core
fivem_license_key: cfxk_buW54VAmD30ha5mb9aOo_1hc0LK

fivem_project_name: Shadowbane RP - STG
fivem_project_desc: YAFM Server ... but different
fivem_locale: en-US
fivem_server_icon: shadowbane-logo-fivem-staging.png
fivem_enforce_game_build: 3258
fivem_use_system_chat_bool: true
fivem_mysql_connection_string_OLD: mysql://root:KoVesq9GxcnqoYi!euLs@localhost/QBCoreFramework_F11C07_STG?charset=utf8mb4

mariadb_root_password: KoVesq9GxcnqoYi!euLs
mariadb_port: 3307
mariadb_name: QBCoreFramework_F11C07_STG
mariadb_charset: utf8mb4
fivem_mysql_connection_string: mysql://root:{{ mariadb_root_password }}@localhost/{{ mariadb_name }}?charset={{ mariadb_charset }}

fivem_voice_config_use_native_audio_boolean: true
fivem_voice_config_use_sending_range_only_boolean: true
fivem_voice_config_default_cycle_string: GRAVE
fivem_voice_config_default_volume_float: 0.3
fivem_voice_config_enable_radio_anim_integer: 1
fivem_voice_config_sync_data_integer: 1

fivem_qbcore_locale_string: en
fivem_qbcore_use_target_boolean: false
fivem_admin_group_name_string: staging_admin
fivem_rcon_password: balls

fivem_docker_network: sbstg_net