# Dockerfile

FROM mariadb:latest

# Install the MariaDB client (mysql and mysqldump)
RUN apt-get update && \
    apt-get install -y mariadb-client && \
    rm -rf /var/lib/apt/lists/*

# Expose the MariaDB port
EXPOSE 3306
